import enum


class decodeCode(enum.Enum):
    RESUBMIT_NICKNAME = 0
    SUBMIT_NICKNAME_SUCCESS=1
    PREDICT_TURN = 2
    UPDATE_DASHBOARD = 3
    QUIT = 4
    DO_NO_THING = 5
    NULL_RECEIVED =6
    DESCRIPTION_RECEIVED_SUCCESS = 7
    ORDER_RECEIVED_SUCCESS = 8
