
API_SEND_NAME = '0'
API_SEND_ORDER = '1'
API_SEND_CONNECTION = '2'
API_SEND_ANSWER = '3'
API_SEND_QUESTION = '4'        
API_SEND_IN_TURN = '5'
API_SEND_RESULT = '6'
API_SEND_QUIT = '7'

API_CANT_DECODE_ANY_MSG = "-1"